services:
  karyo-demo:
    image: karyo-test
    container_name: karyo-test
    build: .
    ports:
      - "8000:8000"
    environment:
      MODEL_ARCH: "maskrcnn_r50_fpn"
    volumes:
      - ./weights_demo:/weights_demo
    command: >
          bash -lc "mkdir -p /weights_demo && curl -L https://github.com/neophoca/test5/releases/download/v0.1.0/maskrcnn_B_ep40.pth -o /weights_demo/model.pth && uvicorn demo.app:app --host 0.0.0.0 --port 8000"